services:
  - type: web
    name: n8n
    env: docker
    plan: starter        # bei Bedarf größer wählen
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-postgres
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-postgres
          property: password
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-postgres
          property: database
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: your-n8n.onrender.com   # später eigene Domain möglich
      - key: WEBHOOK_URL
        value: https://your-n8n.onrender.com/
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin
      - key: TZ
        value: Europe/Berlin
      - key: N8N_ENCRYPTION_KEY       # WICHTIG: selbst setzen (32+ Zeichen)
        sync: false
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 5
databases:
  - name: n8n-postgres
    databaseName: n8n
    plan: free
